#include "input.hpp"

std::map<uint32_t, uint32_t> Input::codeMap = {
#ifdef KEY_ESC
 {KEY_ESC, DEAR_KEY_ESC}, 
#endif
#ifdef KEY_1
 {KEY_1, DEAR_KEY_1}, 
#endif
#ifdef KEY_2
 {KEY_2, DEAR_KEY_2}, 
#endif
#ifdef KEY_3
 {KEY_3, DEAR_KEY_3}, 
#endif
#ifdef KEY_4
 {KEY_4, DEAR_KEY_4}, 
#endif
#ifdef KEY_5
 {KEY_5, DEAR_KEY_5}, 
#endif
#ifdef KEY_6
 {KEY_6, DEAR_KEY_6}, 
#endif
#ifdef KEY_7
 {KEY_7, DEAR_KEY_7}, 
#endif
#ifdef KEY_8
 {KEY_8, DEAR_KEY_8}, 
#endif
#ifdef KEY_9
 {KEY_9, DEAR_KEY_9}, 
#endif
#ifdef KEY_0
 {KEY_0, DEAR_KEY_0}, 
#endif
#ifdef KEY_MINUS
 {KEY_MINUS, DEAR_KEY_MINUS}, 
#endif
#ifdef KEY_EQUAL
 {KEY_EQUAL, DEAR_KEY_EQUAL}, 
#endif
#ifdef KEY_BACKSPACE
 {KEY_BACKSPACE, DEAR_KEY_BACKSPACE}, 
#endif
#ifdef KEY_TAB
 {KEY_TAB, DEAR_KEY_TAB}, 
#endif
#ifdef KEY_Q
 {KEY_Q, DEAR_KEY_Q}, 
#endif
#ifdef KEY_W
 {KEY_W, DEAR_KEY_W}, 
#endif
#ifdef KEY_E
 {KEY_E, DEAR_KEY_E}, 
#endif
#ifdef KEY_R
 {KEY_R, DEAR_KEY_R}, 
#endif
#ifdef KEY_T
 {KEY_T, DEAR_KEY_T}, 
#endif
#ifdef KEY_Y
 {KEY_Y, DEAR_KEY_Y}, 
#endif
#ifdef KEY_U
 {KEY_U, DEAR_KEY_U}, 
#endif
#ifdef KEY_I
 {KEY_I, DEAR_KEY_I}, 
#endif
#ifdef KEY_O
 {KEY_O, DEAR_KEY_O}, 
#endif
#ifdef KEY_P
 {KEY_P, DEAR_KEY_P}, 
#endif
#ifdef KEY_LEFTBRACE
 {KEY_LEFTBRACE, DEAR_KEY_LEFTBRACE}, 
#endif
#ifdef KEY_RIGHTBRACE
 {KEY_RIGHTBRACE, DEAR_KEY_RIGHTBRACE}, 
#endif
#ifdef KEY_ENTER
 {KEY_ENTER, DEAR_KEY_ENTER}, 
#endif
#ifdef KEY_LEFTCTRL
 {KEY_LEFTCTRL, DEAR_KEY_LEFTCTRL}, 
#endif
#ifdef KEY_A
 {KEY_A, DEAR_KEY_A}, 
#endif
#ifdef KEY_S
 {KEY_S, DEAR_KEY_S}, 
#endif
#ifdef KEY_D
 {KEY_D, DEAR_KEY_D}, 
#endif
#ifdef KEY_F
 {KEY_F, DEAR_KEY_F}, 
#endif
#ifdef KEY_G
 {KEY_G, DEAR_KEY_G}, 
#endif
#ifdef KEY_H
 {KEY_H, DEAR_KEY_H}, 
#endif
#ifdef KEY_J
 {KEY_J, DEAR_KEY_J}, 
#endif
#ifdef KEY_K
 {KEY_K, DEAR_KEY_K}, 
#endif
#ifdef KEY_L
 {KEY_L, DEAR_KEY_L}, 
#endif
#ifdef KEY_SEMICOLON
 {KEY_SEMICOLON, DEAR_KEY_SEMICOLON}, 
#endif
#ifdef KEY_APOSTROPHE
 {KEY_APOSTROPHE, DEAR_KEY_APOSTROPHE}, 
#endif
#ifdef KEY_GRAVE
 {KEY_GRAVE, DEAR_KEY_GRAVE}, 
#endif
#ifdef KEY_LEFTSHIFT
 {KEY_LEFTSHIFT, DEAR_KEY_LEFTSHIFT}, 
#endif
#ifdef KEY_BACKSLASH
 {KEY_BACKSLASH, DEAR_KEY_BACKSLASH}, 
#endif
#ifdef KEY_Z
 {KEY_Z, DEAR_KEY_Z}, 
#endif
#ifdef KEY_X
 {KEY_X, DEAR_KEY_X}, 
#endif
#ifdef KEY_C
 {KEY_C, DEAR_KEY_C}, 
#endif
#ifdef KEY_V
 {KEY_V, DEAR_KEY_V}, 
#endif
#ifdef KEY_B
 {KEY_B, DEAR_KEY_B}, 
#endif
#ifdef KEY_N
 {KEY_N, DEAR_KEY_N}, 
#endif
#ifdef KEY_M
 {KEY_M, DEAR_KEY_M}, 
#endif
#ifdef KEY_COMMA
 {KEY_COMMA, DEAR_KEY_COMMA}, 
#endif
#ifdef KEY_DOT
 {KEY_DOT, DEAR_KEY_DOT}, 
#endif
#ifdef KEY_SLASH
 {KEY_SLASH, DEAR_KEY_SLASH}, 
#endif
#ifdef KEY_RIGHTSHIFT
 {KEY_RIGHTSHIFT, DEAR_KEY_RIGHTSHIFT}, 
#endif
#ifdef KEY_KPASTERISK
 {KEY_KPASTERISK, DEAR_KEY_KPASTERISK}, 
#endif
#ifdef KEY_LEFTALT
 {KEY_LEFTALT, DEAR_KEY_LEFTALT}, 
#endif
#ifdef KEY_SPACE
 {KEY_SPACE, DEAR_KEY_SPACE}, 
#endif
#ifdef KEY_CAPSLOCK
 {KEY_CAPSLOCK, DEAR_KEY_CAPSLOCK}, 
#endif
#ifdef KEY_F1
 {KEY_F1, DEAR_KEY_F1}, 
#endif
#ifdef KEY_F2
 {KEY_F2, DEAR_KEY_F2}, 
#endif
#ifdef KEY_F3
 {KEY_F3, DEAR_KEY_F3}, 
#endif
#ifdef KEY_F4
 {KEY_F4, DEAR_KEY_F4}, 
#endif
#ifdef KEY_F5
 {KEY_F5, DEAR_KEY_F5}, 
#endif
#ifdef KEY_F6
 {KEY_F6, DEAR_KEY_F6}, 
#endif
#ifdef KEY_F7
 {KEY_F7, DEAR_KEY_F7}, 
#endif
#ifdef KEY_F8
 {KEY_F8, DEAR_KEY_F8}, 
#endif
#ifdef KEY_F9
 {KEY_F9, DEAR_KEY_F9}, 
#endif
#ifdef KEY_F10
 {KEY_F10, DEAR_KEY_F10}, 
#endif
#ifdef KEY_NUMLOCK
 {KEY_NUMLOCK, DEAR_KEY_NUMLOCK}, 
#endif
#ifdef KEY_SCROLLLOCK
 {KEY_SCROLLLOCK, DEAR_KEY_SCROLLLOCK}, 
#endif
#ifdef KEY_KP7
 {KEY_KP7, DEAR_KEY_KP7}, 
#endif
#ifdef KEY_KP8
 {KEY_KP8, DEAR_KEY_KP8}, 
#endif
#ifdef KEY_KP9
 {KEY_KP9, DEAR_KEY_KP9}, 
#endif
#ifdef KEY_KPMINUS
 {KEY_KPMINUS, DEAR_KEY_KPMINUS}, 
#endif
#ifdef KEY_KP4
 {KEY_KP4, DEAR_KEY_KP4}, 
#endif
#ifdef KEY_KP5
 {KEY_KP5, DEAR_KEY_KP5}, 
#endif
#ifdef KEY_KP6
 {KEY_KP6, DEAR_KEY_KP6}, 
#endif
#ifdef KEY_KPPLUS
 {KEY_KPPLUS, DEAR_KEY_KPPLUS}, 
#endif
#ifdef KEY_KP1
 {KEY_KP1, DEAR_KEY_KP1}, 
#endif
#ifdef KEY_KP2
 {KEY_KP2, DEAR_KEY_KP2}, 
#endif
#ifdef KEY_KP3
 {KEY_KP3, DEAR_KEY_KP3}, 
#endif
#ifdef KEY_KP0
 {KEY_KP0, DEAR_KEY_KP0}, 
#endif
#ifdef KEY_KPDOT
 {KEY_KPDOT, DEAR_KEY_KPDOT}, 
#endif
#ifdef KEY_ZENKAKUHANKAKU
 {KEY_ZENKAKUHANKAKU, DEAR_KEY_ZENKAKUHANKAKU}, 
#endif
#ifdef KEY_102ND
 {KEY_102ND, DEAR_KEY_102ND}, 
#endif
#ifdef KEY_F11
 {KEY_F11, DEAR_KEY_F11}, 
#endif
#ifdef KEY_F12
 {KEY_F12, DEAR_KEY_F12}, 
#endif
#ifdef KEY_RO
 {KEY_RO, DEAR_KEY_RO}, 
#endif
#ifdef KEY_KATAKANA
 {KEY_KATAKANA, DEAR_KEY_KATAKANA}, 
#endif
#ifdef KEY_HIRAGANA
 {KEY_HIRAGANA, DEAR_KEY_HIRAGANA}, 
#endif
#ifdef KEY_HENKAN
 {KEY_HENKAN, DEAR_KEY_HENKAN}, 
#endif
#ifdef KEY_KATAKANAHIRAGANA
 {KEY_KATAKANAHIRAGANA, DEAR_KEY_KATAKANAHIRAGANA}, 
#endif
#ifdef KEY_MUHENKAN
 {KEY_MUHENKAN, DEAR_KEY_MUHENKAN}, 
#endif
#ifdef KEY_KPJPCOMMA
 {KEY_KPJPCOMMA, DEAR_KEY_KPJPCOMMA}, 
#endif
#ifdef KEY_KPENTER
 {KEY_KPENTER, DEAR_KEY_KPENTER}, 
#endif
#ifdef KEY_RIGHTCTRL
 {KEY_RIGHTCTRL, DEAR_KEY_RIGHTCTRL}, 
#endif
#ifdef KEY_KPSLASH
 {KEY_KPSLASH, DEAR_KEY_KPSLASH}, 
#endif
#ifdef KEY_SYSRQ
 {KEY_SYSRQ, DEAR_KEY_SYSRQ}, 
#endif
#ifdef KEY_RIGHTALT
 {KEY_RIGHTALT, DEAR_KEY_RIGHTALT}, 
#endif
#ifdef KEY_LINEFEED
 {KEY_LINEFEED, DEAR_KEY_LINEFEED}, 
#endif
#ifdef KEY_HOME
 {KEY_HOME, DEAR_KEY_HOME}, 
#endif
#ifdef KEY_UP
 {KEY_UP, DEAR_KEY_UP}, 
#endif
#ifdef KEY_PAGEUP
 {KEY_PAGEUP, DEAR_KEY_PAGEUP}, 
#endif
#ifdef KEY_LEFT
 {KEY_LEFT, DEAR_KEY_LEFT}, 
#endif
#ifdef KEY_RIGHT
 {KEY_RIGHT, DEAR_KEY_RIGHT}, 
#endif
#ifdef KEY_END
 {KEY_END, DEAR_KEY_END}, 
#endif
#ifdef KEY_DOWN
 {KEY_DOWN, DEAR_KEY_DOWN}, 
#endif
#ifdef KEY_PAGEDOWN
 {KEY_PAGEDOWN, DEAR_KEY_PAGEDOWN}, 
#endif
#ifdef KEY_INSERT
 {KEY_INSERT, DEAR_KEY_INSERT}, 
#endif
#ifdef KEY_DELETE
 {KEY_DELETE, DEAR_KEY_DELETE}, 
#endif
#ifdef KEY_MACRO
 {KEY_MACRO, DEAR_KEY_MACRO}, 
#endif
#ifdef KEY_MUTE
 {KEY_MUTE, DEAR_KEY_MUTE}, 
#endif
#ifdef KEY_VOLUMEDOWN
 {KEY_VOLUMEDOWN, DEAR_KEY_VOLUMEDOWN}, 
#endif
#ifdef KEY_VOLUMEUP
 {KEY_VOLUMEUP, DEAR_KEY_VOLUMEUP}, 
#endif
#ifdef KEY_POWER
 {KEY_POWER, DEAR_KEY_POWER}, 
#endif
#ifdef KEY_KPEQUAL
 {KEY_KPEQUAL, DEAR_KEY_KPEQUAL}, 
#endif
#ifdef KEY_KPPLUSMINUS
 {KEY_KPPLUSMINUS, DEAR_KEY_KPPLUSMINUS}, 
#endif
#ifdef KEY_PAUSE
 {KEY_PAUSE, DEAR_KEY_PAUSE}, 
#endif
#ifdef KEY_SCALE
 {KEY_SCALE, DEAR_KEY_SCALE}, 
#endif
#ifdef KEY_KPCOMMA
 {KEY_KPCOMMA, DEAR_KEY_KPCOMMA}, 
#endif
#ifdef KEY_HANGEUL
 {KEY_HANGEUL, DEAR_KEY_HANGEUL}, 
#endif
#ifdef KEY_HANGUEL
 {KEY_HANGUEL, DEAR_KEY_HANGUEL}, 
#endif
#ifdef KEY_HANJA
 {KEY_HANJA, DEAR_KEY_HANJA}, 
#endif
#ifdef KEY_YEN
 {KEY_YEN, DEAR_KEY_YEN}, 
#endif
#ifdef KEY_LEFTMETA
 {KEY_LEFTMETA, DEAR_KEY_LEFTMETA}, 
#endif
#ifdef KEY_RIGHTMETA
 {KEY_RIGHTMETA, DEAR_KEY_RIGHTMETA}, 
#endif
#ifdef KEY_COMPOSE
 {KEY_COMPOSE, DEAR_KEY_COMPOSE}, 
#endif
#ifdef KEY_STOP
 {KEY_STOP, DEAR_KEY_STOP}, 
#endif
#ifdef KEY_AGAIN
 {KEY_AGAIN, DEAR_KEY_AGAIN}, 
#endif
#ifdef KEY_PROPS
 {KEY_PROPS, DEAR_KEY_PROPS}, 
#endif
#ifdef KEY_UNDO
 {KEY_UNDO, DEAR_KEY_UNDO}, 
#endif
#ifdef KEY_FRONT
 {KEY_FRONT, DEAR_KEY_FRONT}, 
#endif
#ifdef KEY_COPY
 {KEY_COPY, DEAR_KEY_COPY}, 
#endif
#ifdef KEY_OPEN
 {KEY_OPEN, DEAR_KEY_OPEN}, 
#endif
#ifdef KEY_PASTE
 {KEY_PASTE, DEAR_KEY_PASTE}, 
#endif
#ifdef KEY_FIND
 {KEY_FIND, DEAR_KEY_FIND}, 
#endif
#ifdef KEY_CUT
 {KEY_CUT, DEAR_KEY_CUT}, 
#endif
#ifdef KEY_HELP
 {KEY_HELP, DEAR_KEY_HELP}, 
#endif
#ifdef KEY_MENU
 {KEY_MENU, DEAR_KEY_MENU}, 
#endif
#ifdef KEY_CALC
 {KEY_CALC, DEAR_KEY_CALC}, 
#endif
#ifdef KEY_SETUP
 {KEY_SETUP, DEAR_KEY_SETUP}, 
#endif
#ifdef KEY_SLEEP
 {KEY_SLEEP, DEAR_KEY_SLEEP}, 
#endif
#ifdef KEY_WAKEUP
 {KEY_WAKEUP, DEAR_KEY_WAKEUP}, 
#endif
#ifdef KEY_FILE
 {KEY_FILE, DEAR_KEY_FILE}, 
#endif
#ifdef KEY_SENDFILE
 {KEY_SENDFILE, DEAR_KEY_SENDFILE}, 
#endif
#ifdef KEY_DELETEFILE
 {KEY_DELETEFILE, DEAR_KEY_DELETEFILE}, 
#endif
#ifdef KEY_XFER
 {KEY_XFER, DEAR_KEY_XFER}, 
#endif
#ifdef KEY_PROG1
 {KEY_PROG1, DEAR_KEY_PROG1}, 
#endif
#ifdef KEY_PROG2
 {KEY_PROG2, DEAR_KEY_PROG2}, 
#endif
#ifdef KEY_WWW
 {KEY_WWW, DEAR_KEY_WWW}, 
#endif
#ifdef KEY_MSDOS
 {KEY_MSDOS, DEAR_KEY_MSDOS}, 
#endif
#ifdef KEY_COFFEE
 {KEY_COFFEE, DEAR_KEY_COFFEE}, 
#endif
#ifdef KEY_SCREENLOCK
 {KEY_SCREENLOCK, DEAR_KEY_SCREENLOCK}, 
#endif
#ifdef KEY_ROTATE_DISPLAY
 {KEY_ROTATE_DISPLAY, DEAR_KEY_ROTATE_DISPLAY}, 
#endif
#ifdef KEY_DIRECTION
 {KEY_DIRECTION, DEAR_KEY_DIRECTION}, 
#endif
#ifdef KEY_CYCLEWINDOWS
 {KEY_CYCLEWINDOWS, DEAR_KEY_CYCLEWINDOWS}, 
#endif
#ifdef KEY_MAIL
 {KEY_MAIL, DEAR_KEY_MAIL}, 
#endif
#ifdef KEY_BOOKMARKS
 {KEY_BOOKMARKS, DEAR_KEY_BOOKMARKS}, 
#endif
#ifdef KEY_COMPUTER
 {KEY_COMPUTER, DEAR_KEY_COMPUTER}, 
#endif
#ifdef KEY_BACK
 {KEY_BACK, DEAR_KEY_BACK}, 
#endif
#ifdef KEY_FORWARD
 {KEY_FORWARD, DEAR_KEY_FORWARD}, 
#endif
#ifdef KEY_CLOSECD
 {KEY_CLOSECD, DEAR_KEY_CLOSECD}, 
#endif
#ifdef KEY_EJECTCD
 {KEY_EJECTCD, DEAR_KEY_EJECTCD}, 
#endif
#ifdef KEY_EJECTCLOSECD
 {KEY_EJECTCLOSECD, DEAR_KEY_EJECTCLOSECD}, 
#endif
#ifdef KEY_NEXTSONG
 {KEY_NEXTSONG, DEAR_KEY_NEXTSONG}, 
#endif
#ifdef KEY_PLAYPAUSE
 {KEY_PLAYPAUSE, DEAR_KEY_PLAYPAUSE}, 
#endif
#ifdef KEY_PREVIOUSSONG
 {KEY_PREVIOUSSONG, DEAR_KEY_PREVIOUSSONG}, 
#endif
#ifdef KEY_STOPCD
 {KEY_STOPCD, DEAR_KEY_STOPCD}, 
#endif
#ifdef KEY_RECORD
 {KEY_RECORD, DEAR_KEY_RECORD}, 
#endif
#ifdef KEY_REWIND
 {KEY_REWIND, DEAR_KEY_REWIND}, 
#endif
#ifdef KEY_PHONE
 {KEY_PHONE, DEAR_KEY_PHONE}, 
#endif
#ifdef KEY_ISO
 {KEY_ISO, DEAR_KEY_ISO}, 
#endif
#ifdef KEY_CONFIG
 {KEY_CONFIG, DEAR_KEY_CONFIG}, 
#endif
#ifdef KEY_HOMEPAGE
 {KEY_HOMEPAGE, DEAR_KEY_HOMEPAGE}, 
#endif
#ifdef KEY_REFRESH
 {KEY_REFRESH, DEAR_KEY_REFRESH}, 
#endif
#ifdef KEY_EXIT
 {KEY_EXIT, DEAR_KEY_EXIT}, 
#endif
#ifdef KEY_MOVE
 {KEY_MOVE, DEAR_KEY_MOVE}, 
#endif
#ifdef KEY_EDIT
 {KEY_EDIT, DEAR_KEY_EDIT}, 
#endif
#ifdef KEY_SCROLLUP
 {KEY_SCROLLUP, DEAR_KEY_SCROLLUP}, 
#endif
#ifdef KEY_SCROLLDOWN
 {KEY_SCROLLDOWN, DEAR_KEY_SCROLLDOWN}, 
#endif
#ifdef KEY_KPLEFTPAREN
 {KEY_KPLEFTPAREN, DEAR_KEY_KPLEFTPAREN}, 
#endif
#ifdef KEY_KPRIGHTPAREN
 {KEY_KPRIGHTPAREN, DEAR_KEY_KPRIGHTPAREN}, 
#endif
#ifdef KEY_NEW
 {KEY_NEW, DEAR_KEY_NEW}, 
#endif
#ifdef KEY_REDO
 {KEY_REDO, DEAR_KEY_REDO}, 
#endif
#ifdef KEY_F13
 {KEY_F13, DEAR_KEY_F13}, 
#endif
#ifdef KEY_F14
 {KEY_F14, DEAR_KEY_F14}, 
#endif
#ifdef KEY_F15
 {KEY_F15, DEAR_KEY_F15}, 
#endif
#ifdef KEY_F16
 {KEY_F16, DEAR_KEY_F16}, 
#endif
#ifdef KEY_F17
 {KEY_F17, DEAR_KEY_F17}, 
#endif
#ifdef KEY_F18
 {KEY_F18, DEAR_KEY_F18}, 
#endif
#ifdef KEY_F19
 {KEY_F19, DEAR_KEY_F19}, 
#endif
#ifdef KEY_F20
 {KEY_F20, DEAR_KEY_F20}, 
#endif
#ifdef KEY_F21
 {KEY_F21, DEAR_KEY_F21}, 
#endif
#ifdef KEY_F22
 {KEY_F22, DEAR_KEY_F22}, 
#endif
#ifdef KEY_F23
 {KEY_F23, DEAR_KEY_F23}, 
#endif
#ifdef KEY_F24
 {KEY_F24, DEAR_KEY_F24}, 
#endif
#ifdef KEY_PLAYCD
 {KEY_PLAYCD, DEAR_KEY_PLAYCD}, 
#endif
#ifdef KEY_PAUSECD
 {KEY_PAUSECD, DEAR_KEY_PAUSECD}, 
#endif
#ifdef KEY_PROG3
 {KEY_PROG3, DEAR_KEY_PROG3}, 
#endif
#ifdef KEY_PROG4
 {KEY_PROG4, DEAR_KEY_PROG4}, 
#endif
#ifdef KEY_DASHBOARD
 {KEY_DASHBOARD, DEAR_KEY_DASHBOARD}, 
#endif
#ifdef KEY_SUSPEND
 {KEY_SUSPEND, DEAR_KEY_SUSPEND}, 
#endif
#ifdef KEY_CLOSE
 {KEY_CLOSE, DEAR_KEY_CLOSE}, 
#endif
#ifdef KEY_PLAY
 {KEY_PLAY, DEAR_KEY_PLAY}, 
#endif
#ifdef KEY_FASTFORWARD
 {KEY_FASTFORWARD, DEAR_KEY_FASTFORWARD}, 
#endif
#ifdef KEY_BASSBOOST
 {KEY_BASSBOOST, DEAR_KEY_BASSBOOST}, 
#endif
#ifdef KEY_PRINT
 {KEY_PRINT, DEAR_KEY_PRINT}, 
#endif
#ifdef KEY_HP
 {KEY_HP, DEAR_KEY_HP}, 
#endif
#ifdef KEY_CAMERA
 {KEY_CAMERA, DEAR_KEY_CAMERA}, 
#endif
#ifdef KEY_SOUND
 {KEY_SOUND, DEAR_KEY_SOUND}, 
#endif
#ifdef KEY_QUESTION
 {KEY_QUESTION, DEAR_KEY_QUESTION}, 
#endif
#ifdef KEY_EMAIL
 {KEY_EMAIL, DEAR_KEY_EMAIL}, 
#endif
#ifdef KEY_CHAT
 {KEY_CHAT, DEAR_KEY_CHAT}, 
#endif
#ifdef KEY_SEARCH
 {KEY_SEARCH, DEAR_KEY_SEARCH}, 
#endif
#ifdef KEY_CONNECT
 {KEY_CONNECT, DEAR_KEY_CONNECT}, 
#endif
#ifdef KEY_FINANCE
 {KEY_FINANCE, DEAR_KEY_FINANCE}, 
#endif
#ifdef KEY_SPORT
 {KEY_SPORT, DEAR_KEY_SPORT}, 
#endif
#ifdef KEY_SHOP
 {KEY_SHOP, DEAR_KEY_SHOP}, 
#endif
#ifdef KEY_ALTERASE
 {KEY_ALTERASE, DEAR_KEY_ALTERASE}, 
#endif
#ifdef KEY_CANCEL
 {KEY_CANCEL, DEAR_KEY_CANCEL}, 
#endif
#ifdef KEY_BRIGHTNESSDOWN
 {KEY_BRIGHTNESSDOWN, DEAR_KEY_BRIGHTNESSDOWN}, 
#endif
#ifdef KEY_BRIGHTNESSUP
 {KEY_BRIGHTNESSUP, DEAR_KEY_BRIGHTNESSUP}, 
#endif
#ifdef KEY_MEDIA
 {KEY_MEDIA, DEAR_KEY_MEDIA}, 
#endif
#ifdef KEY_SWITCHVIDEOMODE
 {KEY_SWITCHVIDEOMODE, DEAR_KEY_SWITCHVIDEOMODE}, 
#endif
#ifdef KEY_KBDILLUMTOGGLE
 {KEY_KBDILLUMTOGGLE, DEAR_KEY_KBDILLUMTOGGLE}, 
#endif
#ifdef KEY_KBDILLUMDOWN
 {KEY_KBDILLUMDOWN, DEAR_KEY_KBDILLUMDOWN}, 
#endif
#ifdef KEY_KBDILLUMUP
 {KEY_KBDILLUMUP, DEAR_KEY_KBDILLUMUP}, 
#endif
#ifdef KEY_SEND
 {KEY_SEND, DEAR_KEY_SEND}, 
#endif
#ifdef KEY_REPLY
 {KEY_REPLY, DEAR_KEY_REPLY}, 
#endif
#ifdef KEY_FORWARDMAIL
 {KEY_FORWARDMAIL, DEAR_KEY_FORWARDMAIL}, 
#endif
#ifdef KEY_SAVE
 {KEY_SAVE, DEAR_KEY_SAVE}, 
#endif
#ifdef KEY_DOCUMENTS
 {KEY_DOCUMENTS, DEAR_KEY_DOCUMENTS}, 
#endif
#ifdef KEY_BATTERY
 {KEY_BATTERY, DEAR_KEY_BATTERY}, 
#endif
#ifdef KEY_BLUETOOTH
 {KEY_BLUETOOTH, DEAR_KEY_BLUETOOTH}, 
#endif
#ifdef KEY_WLAN
 {KEY_WLAN, DEAR_KEY_WLAN}, 
#endif
#ifdef KEY_UWB
 {KEY_UWB, DEAR_KEY_UWB}, 
#endif
#ifdef KEY_UNKNOWN
 {KEY_UNKNOWN, DEAR_KEY_UNKNOWN}, 
#endif
#ifdef KEY_VIDEO_NEXT
 {KEY_VIDEO_NEXT, DEAR_KEY_VIDEO_NEXT}, 
#endif
#ifdef KEY_VIDEO_PREV
 {KEY_VIDEO_PREV, DEAR_KEY_VIDEO_PREV}, 
#endif
#ifdef KEY_BRIGHTNESS_CYCLE
 {KEY_BRIGHTNESS_CYCLE, DEAR_KEY_BRIGHTNESS_CYCLE}, 
#endif
#ifdef KEY_BRIGHTNESS_AUTO
 {KEY_BRIGHTNESS_AUTO, DEAR_KEY_BRIGHTNESS_AUTO}, 
#endif
#ifdef KEY_BRIGHTNESS_ZERO
 {KEY_BRIGHTNESS_ZERO, DEAR_KEY_BRIGHTNESS_ZERO}, 
#endif
#ifdef KEY_DISPLAY_OFF
 {KEY_DISPLAY_OFF, DEAR_KEY_DISPLAY_OFF}, 
#endif
#ifdef KEY_WWAN
 {KEY_WWAN, DEAR_KEY_WWAN}, 
#endif
#ifdef KEY_WIMAX
 {KEY_WIMAX, DEAR_KEY_WIMAX}, 
#endif
#ifdef KEY_RFKILL
 {KEY_RFKILL, DEAR_KEY_RFKILL}, 
#endif
#ifdef KEY_MICMUTE
 {KEY_MICMUTE, DEAR_KEY_MICMUTE}, 
#endif
#ifdef BTN_MISC
 {BTN_MISC, DEAR_BTN_MISC}, 
#endif
#ifdef BTN_0
 {BTN_0, DEAR_BTN_0}, 
#endif
#ifdef BTN_1
 {BTN_1, DEAR_BTN_1}, 
#endif
#ifdef BTN_2
 {BTN_2, DEAR_BTN_2}, 
#endif
#ifdef BTN_3
 {BTN_3, DEAR_BTN_3}, 
#endif
#ifdef BTN_4
 {BTN_4, DEAR_BTN_4}, 
#endif
#ifdef BTN_5
 {BTN_5, DEAR_BTN_5}, 
#endif
#ifdef BTN_6
 {BTN_6, DEAR_BTN_6}, 
#endif
#ifdef BTN_7
 {BTN_7, DEAR_BTN_7}, 
#endif
#ifdef BTN_8
 {BTN_8, DEAR_BTN_8}, 
#endif
#ifdef BTN_9
 {BTN_9, DEAR_BTN_9}, 
#endif
#ifdef BTN_MOUSE
 {BTN_MOUSE, DEAR_BTN_MOUSE}, 
#endif
#ifdef BTN_LEFT
 {BTN_LEFT, DEAR_BTN_LEFT}, 
#endif
#ifdef BTN_RIGHT
 {BTN_RIGHT, DEAR_BTN_RIGHT}, 
#endif
#ifdef BTN_MIDDLE
 {BTN_MIDDLE, DEAR_BTN_MIDDLE}, 
#endif
#ifdef BTN_SIDE
 {BTN_SIDE, DEAR_BTN_SIDE}, 
#endif
#ifdef BTN_EXTRA
 {BTN_EXTRA, DEAR_BTN_EXTRA}, 
#endif
#ifdef BTN_FORWARD
 {BTN_FORWARD, DEAR_BTN_FORWARD}, 
#endif
#ifdef BTN_BACK
 {BTN_BACK, DEAR_BTN_BACK}, 
#endif
#ifdef BTN_TASK
 {BTN_TASK, DEAR_BTN_TASK}, 
#endif
#ifdef BTN_JOYSTICK
 {BTN_JOYSTICK, DEAR_BTN_JOYSTICK}, 
#endif
#ifdef BTN_TRIGGER
 {BTN_TRIGGER, DEAR_BTN_TRIGGER}, 
#endif
#ifdef BTN_THUMB
 {BTN_THUMB, DEAR_BTN_THUMB}, 
#endif
#ifdef BTN_THUMB2
 {BTN_THUMB2, DEAR_BTN_THUMB2}, 
#endif
#ifdef BTN_TOP
 {BTN_TOP, DEAR_BTN_TOP}, 
#endif
#ifdef BTN_TOP2
 {BTN_TOP2, DEAR_BTN_TOP2}, 
#endif
#ifdef BTN_PINKIE
 {BTN_PINKIE, DEAR_BTN_PINKIE}, 
#endif
#ifdef BTN_BASE
 {BTN_BASE, DEAR_BTN_BASE}, 
#endif
#ifdef BTN_BASE2
 {BTN_BASE2, DEAR_BTN_BASE2}, 
#endif
#ifdef BTN_BASE3
 {BTN_BASE3, DEAR_BTN_BASE3}, 
#endif
#ifdef BTN_BASE4
 {BTN_BASE4, DEAR_BTN_BASE4}, 
#endif
#ifdef BTN_BASE5
 {BTN_BASE5, DEAR_BTN_BASE5}, 
#endif
#ifdef BTN_BASE6
 {BTN_BASE6, DEAR_BTN_BASE6}, 
#endif
#ifdef BTN_DEAD
 {BTN_DEAD, DEAR_BTN_DEAD}, 
#endif
#ifdef BTN_GAMEPAD
 {BTN_GAMEPAD, DEAR_BTN_GAMEPAD}, 
#endif
#ifdef BTN_SOUTH
 {BTN_SOUTH, DEAR_BTN_SOUTH}, 
#endif
#ifdef BTN_A
 {BTN_A, DEAR_BTN_A}, 
#endif
#ifdef BTN_EAST
 {BTN_EAST, DEAR_BTN_EAST}, 
#endif
#ifdef BTN_B
 {BTN_B, DEAR_BTN_B}, 
#endif
#ifdef BTN_C
 {BTN_C, DEAR_BTN_C}, 
#endif
#ifdef BTN_NORTH
 {BTN_NORTH, DEAR_BTN_NORTH}, 
#endif
#ifdef BTN_X
 {BTN_X, DEAR_BTN_X}, 
#endif
#ifdef BTN_WEST
 {BTN_WEST, DEAR_BTN_WEST}, 
#endif
#ifdef BTN_Y
 {BTN_Y, DEAR_BTN_Y}, 
#endif
#ifdef BTN_Z
 {BTN_Z, DEAR_BTN_Z}, 
#endif
#ifdef BTN_TL
 {BTN_TL, DEAR_BTN_TL}, 
#endif
#ifdef BTN_TR
 {BTN_TR, DEAR_BTN_TR}, 
#endif
#ifdef BTN_TL2
 {BTN_TL2, DEAR_BTN_TL2}, 
#endif
#ifdef BTN_TR2
 {BTN_TR2, DEAR_BTN_TR2}, 
#endif
#ifdef BTN_SELECT
 {BTN_SELECT, DEAR_BTN_SELECT}, 
#endif
#ifdef BTN_START
 {BTN_START, DEAR_BTN_START}, 
#endif
#ifdef BTN_MODE
 {BTN_MODE, DEAR_BTN_MODE}, 
#endif
#ifdef BTN_THUMBL
 {BTN_THUMBL, DEAR_BTN_THUMBL}, 
#endif
#ifdef BTN_THUMBR
 {BTN_THUMBR, DEAR_BTN_THUMBR}, 
#endif
#ifdef BTN_DIGI
 {BTN_DIGI, DEAR_BTN_DIGI}, 
#endif
#ifdef BTN_TOOL_PEN
 {BTN_TOOL_PEN, DEAR_BTN_TOOL_PEN}, 
#endif
#ifdef BTN_TOOL_RUBBER
 {BTN_TOOL_RUBBER, DEAR_BTN_TOOL_RUBBER}, 
#endif
#ifdef BTN_TOOL_BRUSH
 {BTN_TOOL_BRUSH, DEAR_BTN_TOOL_BRUSH}, 
#endif
#ifdef BTN_TOOL_PENCIL
 {BTN_TOOL_PENCIL, DEAR_BTN_TOOL_PENCIL}, 
#endif
#ifdef BTN_TOOL_AIRBRUSH
 {BTN_TOOL_AIRBRUSH, DEAR_BTN_TOOL_AIRBRUSH}, 
#endif
#ifdef BTN_TOOL_FINGER
 {BTN_TOOL_FINGER, DEAR_BTN_TOOL_FINGER}, 
#endif
#ifdef BTN_TOOL_MOUSE
 {BTN_TOOL_MOUSE, DEAR_BTN_TOOL_MOUSE}, 
#endif
#ifdef BTN_TOOL_LENS
 {BTN_TOOL_LENS, DEAR_BTN_TOOL_LENS}, 
#endif
#ifdef BTN_TOOL_QUINTTAP
 {BTN_TOOL_QUINTTAP, DEAR_BTN_TOOL_QUINTTAP}, 
#endif
#ifdef BTN_TOUCH
 {BTN_TOUCH, DEAR_BTN_TOUCH}, 
#endif
#ifdef BTN_STYLUS
 {BTN_STYLUS, DEAR_BTN_STYLUS}, 
#endif
#ifdef BTN_STYLUS2
 {BTN_STYLUS2, DEAR_BTN_STYLUS2}, 
#endif
#ifdef BTN_TOOL_DOUBLETAP
 {BTN_TOOL_DOUBLETAP, DEAR_BTN_TOOL_DOUBLETAP}, 
#endif
#ifdef BTN_TOOL_TRIPLETAP
 {BTN_TOOL_TRIPLETAP, DEAR_BTN_TOOL_TRIPLETAP}, 
#endif
#ifdef BTN_TOOL_QUADTAP
 {BTN_TOOL_QUADTAP, DEAR_BTN_TOOL_QUADTAP}, 
#endif
#ifdef BTN_WHEEL
 {BTN_WHEEL, DEAR_BTN_WHEEL}, 
#endif
#ifdef BTN_GEAR_DOWN
 {BTN_GEAR_DOWN, DEAR_BTN_GEAR_DOWN}, 
#endif
#ifdef BTN_GEAR_UP
 {BTN_GEAR_UP, DEAR_BTN_GEAR_UP}, 
#endif
#ifdef KEY_OK
 {KEY_OK, DEAR_KEY_OK}, 
#endif
#ifdef KEY_SELECT
 {KEY_SELECT, DEAR_KEY_SELECT}, 
#endif
#ifdef KEY_GOTO
 {KEY_GOTO, DEAR_KEY_GOTO}, 
#endif
#ifdef KEY_CLEAR
 {KEY_CLEAR, DEAR_KEY_CLEAR}, 
#endif
#ifdef KEY_POWER2
 {KEY_POWER2, DEAR_KEY_POWER2}, 
#endif
#ifdef KEY_OPTION
 {KEY_OPTION, DEAR_KEY_OPTION}, 
#endif
#ifdef KEY_INFO
 {KEY_INFO, DEAR_KEY_INFO}, 
#endif
#ifdef KEY_TIME
 {KEY_TIME, DEAR_KEY_TIME}, 
#endif
#ifdef KEY_VENDOR
 {KEY_VENDOR, DEAR_KEY_VENDOR}, 
#endif
#ifdef KEY_ARCHIVE
 {KEY_ARCHIVE, DEAR_KEY_ARCHIVE}, 
#endif
#ifdef KEY_PROGRAM
 {KEY_PROGRAM, DEAR_KEY_PROGRAM}, 
#endif
#ifdef KEY_CHANNEL
 {KEY_CHANNEL, DEAR_KEY_CHANNEL}, 
#endif
#ifdef KEY_FAVORITES
 {KEY_FAVORITES, DEAR_KEY_FAVORITES}, 
#endif
#ifdef KEY_EPG
 {KEY_EPG, DEAR_KEY_EPG}, 
#endif
#ifdef KEY_PVR
 {KEY_PVR, DEAR_KEY_PVR}, 
#endif
#ifdef KEY_MHP
 {KEY_MHP, DEAR_KEY_MHP}, 
#endif
#ifdef KEY_LANGUAGE
 {KEY_LANGUAGE, DEAR_KEY_LANGUAGE}, 
#endif
#ifdef KEY_TITLE
 {KEY_TITLE, DEAR_KEY_TITLE}, 
#endif
#ifdef KEY_SUBTITLE
 {KEY_SUBTITLE, DEAR_KEY_SUBTITLE}, 
#endif
#ifdef KEY_ANGLE
 {KEY_ANGLE, DEAR_KEY_ANGLE}, 
#endif
#ifdef KEY_ZOOM
 {KEY_ZOOM, DEAR_KEY_ZOOM}, 
#endif
#ifdef KEY_MODE
 {KEY_MODE, DEAR_KEY_MODE}, 
#endif
#ifdef KEY_KEYBOARD
 {KEY_KEYBOARD, DEAR_KEY_KEYBOARD}, 
#endif
#ifdef KEY_SCREEN
 {KEY_SCREEN, DEAR_KEY_SCREEN}, 
#endif
#ifdef KEY_PC
 {KEY_PC, DEAR_KEY_PC}, 
#endif
#ifdef KEY_TV
 {KEY_TV, DEAR_KEY_TV}, 
#endif
#ifdef KEY_TV2
 {KEY_TV2, DEAR_KEY_TV2}, 
#endif
#ifdef KEY_VCR
 {KEY_VCR, DEAR_KEY_VCR}, 
#endif
#ifdef KEY_VCR2
 {KEY_VCR2, DEAR_KEY_VCR2}, 
#endif
#ifdef KEY_SAT
 {KEY_SAT, DEAR_KEY_SAT}, 
#endif
#ifdef KEY_SAT2
 {KEY_SAT2, DEAR_KEY_SAT2}, 
#endif
#ifdef KEY_CD
 {KEY_CD, DEAR_KEY_CD}, 
#endif
#ifdef KEY_TAPE
 {KEY_TAPE, DEAR_KEY_TAPE}, 
#endif
#ifdef KEY_RADIO
 {KEY_RADIO, DEAR_KEY_RADIO}, 
#endif
#ifdef KEY_TUNER
 {KEY_TUNER, DEAR_KEY_TUNER}, 
#endif
#ifdef KEY_PLAYER
 {KEY_PLAYER, DEAR_KEY_PLAYER}, 
#endif
#ifdef KEY_TEXT
 {KEY_TEXT, DEAR_KEY_TEXT}, 
#endif
#ifdef KEY_DVD
 {KEY_DVD, DEAR_KEY_DVD}, 
#endif
#ifdef KEY_AUX
 {KEY_AUX, DEAR_KEY_AUX}, 
#endif
#ifdef KEY_MP3
 {KEY_MP3, DEAR_KEY_MP3}, 
#endif
#ifdef KEY_AUDIO
 {KEY_AUDIO, DEAR_KEY_AUDIO}, 
#endif
#ifdef KEY_VIDEO
 {KEY_VIDEO, DEAR_KEY_VIDEO}, 
#endif
#ifdef KEY_DIRECTORY
 {KEY_DIRECTORY, DEAR_KEY_DIRECTORY}, 
#endif
#ifdef KEY_LIST
 {KEY_LIST, DEAR_KEY_LIST}, 
#endif
#ifdef KEY_MEMO
 {KEY_MEMO, DEAR_KEY_MEMO}, 
#endif
#ifdef KEY_CALENDAR
 {KEY_CALENDAR, DEAR_KEY_CALENDAR}, 
#endif
#ifdef KEY_RED
 {KEY_RED, DEAR_KEY_RED}, 
#endif
#ifdef KEY_GREEN
 {KEY_GREEN, DEAR_KEY_GREEN}, 
#endif
#ifdef KEY_YELLOW
 {KEY_YELLOW, DEAR_KEY_YELLOW}, 
#endif
#ifdef KEY_BLUE
 {KEY_BLUE, DEAR_KEY_BLUE}, 
#endif
#ifdef KEY_CHANNELUP
 {KEY_CHANNELUP, DEAR_KEY_CHANNELUP}, 
#endif
#ifdef KEY_CHANNELDOWN
 {KEY_CHANNELDOWN, DEAR_KEY_CHANNELDOWN}, 
#endif
#ifdef KEY_FIRST
 {KEY_FIRST, DEAR_KEY_FIRST}, 
#endif
#ifdef KEY_LAST
 {KEY_LAST, DEAR_KEY_LAST}, 
#endif
#ifdef KEY_AB
 {KEY_AB, DEAR_KEY_AB}, 
#endif
#ifdef KEY_NEXT
 {KEY_NEXT, DEAR_KEY_NEXT}, 
#endif
#ifdef KEY_RESTART
 {KEY_RESTART, DEAR_KEY_RESTART}, 
#endif
#ifdef KEY_SLOW
 {KEY_SLOW, DEAR_KEY_SLOW}, 
#endif
#ifdef KEY_SHUFFLE
 {KEY_SHUFFLE, DEAR_KEY_SHUFFLE}, 
#endif
#ifdef KEY_BREAK
 {KEY_BREAK, DEAR_KEY_BREAK}, 
#endif
#ifdef KEY_PREVIOUS
 {KEY_PREVIOUS, DEAR_KEY_PREVIOUS}, 
#endif
#ifdef KEY_DIGITS
 {KEY_DIGITS, DEAR_KEY_DIGITS}, 
#endif
#ifdef KEY_TEEN
 {KEY_TEEN, DEAR_KEY_TEEN}, 
#endif
#ifdef KEY_TWEN
 {KEY_TWEN, DEAR_KEY_TWEN}, 
#endif
#ifdef KEY_VIDEOPHONE
 {KEY_VIDEOPHONE, DEAR_KEY_VIDEOPHONE}, 
#endif
#ifdef KEY_GAMES
 {KEY_GAMES, DEAR_KEY_GAMES}, 
#endif
#ifdef KEY_ZOOMIN
 {KEY_ZOOMIN, DEAR_KEY_ZOOMIN}, 
#endif
#ifdef KEY_ZOOMOUT
 {KEY_ZOOMOUT, DEAR_KEY_ZOOMOUT}, 
#endif
#ifdef KEY_ZOOMRESET
 {KEY_ZOOMRESET, DEAR_KEY_ZOOMRESET}, 
#endif
#ifdef KEY_WORDPROCESSOR
 {KEY_WORDPROCESSOR, DEAR_KEY_WORDPROCESSOR}, 
#endif
#ifdef KEY_EDITOR
 {KEY_EDITOR, DEAR_KEY_EDITOR}, 
#endif
#ifdef KEY_SPREADSHEET
 {KEY_SPREADSHEET, DEAR_KEY_SPREADSHEET}, 
#endif
#ifdef KEY_GRAPHICSEDITOR
 {KEY_GRAPHICSEDITOR, DEAR_KEY_GRAPHICSEDITOR}, 
#endif
#ifdef KEY_PRESENTATION
 {KEY_PRESENTATION, DEAR_KEY_PRESENTATION}, 
#endif
#ifdef KEY_DATABASE
 {KEY_DATABASE, DEAR_KEY_DATABASE}, 
#endif
#ifdef KEY_NEWS
 {KEY_NEWS, DEAR_KEY_NEWS}, 
#endif
#ifdef KEY_VOICEMAIL
 {KEY_VOICEMAIL, DEAR_KEY_VOICEMAIL}, 
#endif
#ifdef KEY_ADDRESSBOOK
 {KEY_ADDRESSBOOK, DEAR_KEY_ADDRESSBOOK}, 
#endif
#ifdef KEY_MESSENGER
 {KEY_MESSENGER, DEAR_KEY_MESSENGER}, 
#endif
#ifdef KEY_DISPLAYTOGGLE
 {KEY_DISPLAYTOGGLE, DEAR_KEY_DISPLAYTOGGLE}, 
#endif
#ifdef KEY_BRIGHTNESS_TOGGLE
 {KEY_BRIGHTNESS_TOGGLE, DEAR_KEY_BRIGHTNESS_TOGGLE}, 
#endif
#ifdef KEY_SPELLCHECK
 {KEY_SPELLCHECK, DEAR_KEY_SPELLCHECK}, 
#endif
#ifdef KEY_LOGOFF
 {KEY_LOGOFF, DEAR_KEY_LOGOFF}, 
#endif
#ifdef KEY_DOLLAR
 {KEY_DOLLAR, DEAR_KEY_DOLLAR}, 
#endif
#ifdef KEY_EURO
 {KEY_EURO, DEAR_KEY_EURO}, 
#endif
#ifdef KEY_FRAMEBACK
 {KEY_FRAMEBACK, DEAR_KEY_FRAMEBACK}, 
#endif
#ifdef KEY_FRAMEFORWARD
 {KEY_FRAMEFORWARD, DEAR_KEY_FRAMEFORWARD}, 
#endif
#ifdef KEY_CONTEXT_MENU
 {KEY_CONTEXT_MENU, DEAR_KEY_CONTEXT_MENU}, 
#endif
#ifdef KEY_MEDIA_REPEAT
 {KEY_MEDIA_REPEAT, DEAR_KEY_MEDIA_REPEAT}, 
#endif
#ifdef KEY_10CHANNELSUP
 {KEY_10CHANNELSUP, DEAR_KEY_10CHANNELSUP}, 
#endif
#ifdef KEY_10CHANNELSDOWN
 {KEY_10CHANNELSDOWN, DEAR_KEY_10CHANNELSDOWN}, 
#endif
#ifdef KEY_IMAGES
 {KEY_IMAGES, DEAR_KEY_IMAGES}, 
#endif
#ifdef KEY_DEL_EOL
 {KEY_DEL_EOL, DEAR_KEY_DEL_EOL}, 
#endif
#ifdef KEY_DEL_EOS
 {KEY_DEL_EOS, DEAR_KEY_DEL_EOS}, 
#endif
#ifdef KEY_INS_LINE
 {KEY_INS_LINE, DEAR_KEY_INS_LINE}, 
#endif
#ifdef KEY_DEL_LINE
 {KEY_DEL_LINE, DEAR_KEY_DEL_LINE}, 
#endif
#ifdef KEY_FN
 {KEY_FN, DEAR_KEY_FN}, 
#endif
#ifdef KEY_FN_ESC
 {KEY_FN_ESC, DEAR_KEY_FN_ESC}, 
#endif
#ifdef KEY_FN_F1
 {KEY_FN_F1, DEAR_KEY_FN_F1}, 
#endif
#ifdef KEY_FN_F2
 {KEY_FN_F2, DEAR_KEY_FN_F2}, 
#endif
#ifdef KEY_FN_F3
 {KEY_FN_F3, DEAR_KEY_FN_F3}, 
#endif
#ifdef KEY_FN_F4
 {KEY_FN_F4, DEAR_KEY_FN_F4}, 
#endif
#ifdef KEY_FN_F5
 {KEY_FN_F5, DEAR_KEY_FN_F5}, 
#endif
#ifdef KEY_FN_F6
 {KEY_FN_F6, DEAR_KEY_FN_F6}, 
#endif
#ifdef KEY_FN_F7
 {KEY_FN_F7, DEAR_KEY_FN_F7}, 
#endif
#ifdef KEY_FN_F8
 {KEY_FN_F8, DEAR_KEY_FN_F8}, 
#endif
#ifdef KEY_FN_F9
 {KEY_FN_F9, DEAR_KEY_FN_F9}, 
#endif
#ifdef KEY_FN_F10
 {KEY_FN_F10, DEAR_KEY_FN_F10}, 
#endif
#ifdef KEY_FN_F11
 {KEY_FN_F11, DEAR_KEY_FN_F11}, 
#endif
#ifdef KEY_FN_F12
 {KEY_FN_F12, DEAR_KEY_FN_F12}, 
#endif
#ifdef KEY_FN_1
 {KEY_FN_1, DEAR_KEY_FN_1}, 
#endif
#ifdef KEY_FN_2
 {KEY_FN_2, DEAR_KEY_FN_2}, 
#endif
#ifdef KEY_FN_D
 {KEY_FN_D, DEAR_KEY_FN_D}, 
#endif
#ifdef KEY_FN_E
 {KEY_FN_E, DEAR_KEY_FN_E}, 
#endif
#ifdef KEY_FN_F
 {KEY_FN_F, DEAR_KEY_FN_F}, 
#endif
#ifdef KEY_FN_S
 {KEY_FN_S, DEAR_KEY_FN_S}, 
#endif
#ifdef KEY_FN_B
 {KEY_FN_B, DEAR_KEY_FN_B}, 
#endif
#ifdef KEY_BRL_DOT1
 {KEY_BRL_DOT1, DEAR_KEY_BRL_DOT1}, 
#endif
#ifdef KEY_BRL_DOT2
 {KEY_BRL_DOT2, DEAR_KEY_BRL_DOT2}, 
#endif
#ifdef KEY_BRL_DOT3
 {KEY_BRL_DOT3, DEAR_KEY_BRL_DOT3}, 
#endif
#ifdef KEY_BRL_DOT4
 {KEY_BRL_DOT4, DEAR_KEY_BRL_DOT4}, 
#endif
#ifdef KEY_BRL_DOT5
 {KEY_BRL_DOT5, DEAR_KEY_BRL_DOT5}, 
#endif
#ifdef KEY_BRL_DOT6
 {KEY_BRL_DOT6, DEAR_KEY_BRL_DOT6}, 
#endif
#ifdef KEY_BRL_DOT7
 {KEY_BRL_DOT7, DEAR_KEY_BRL_DOT7}, 
#endif
#ifdef KEY_BRL_DOT8
 {KEY_BRL_DOT8, DEAR_KEY_BRL_DOT8}, 
#endif
#ifdef KEY_BRL_DOT9
 {KEY_BRL_DOT9, DEAR_KEY_BRL_DOT9}, 
#endif
#ifdef KEY_BRL_DOT10
 {KEY_BRL_DOT10, DEAR_KEY_BRL_DOT10}, 
#endif
#ifdef KEY_NUMERIC_0
 {KEY_NUMERIC_0, DEAR_KEY_NUMERIC_0}, 
#endif
#ifdef KEY_NUMERIC_1
 {KEY_NUMERIC_1, DEAR_KEY_NUMERIC_1}, 
#endif
#ifdef KEY_NUMERIC_2
 {KEY_NUMERIC_2, DEAR_KEY_NUMERIC_2}, 
#endif
#ifdef KEY_NUMERIC_3
 {KEY_NUMERIC_3, DEAR_KEY_NUMERIC_3}, 
#endif
#ifdef KEY_NUMERIC_4
 {KEY_NUMERIC_4, DEAR_KEY_NUMERIC_4}, 
#endif
#ifdef KEY_NUMERIC_5
 {KEY_NUMERIC_5, DEAR_KEY_NUMERIC_5}, 
#endif
#ifdef KEY_NUMERIC_6
 {KEY_NUMERIC_6, DEAR_KEY_NUMERIC_6}, 
#endif
#ifdef KEY_NUMERIC_7
 {KEY_NUMERIC_7, DEAR_KEY_NUMERIC_7}, 
#endif
#ifdef KEY_NUMERIC_8
 {KEY_NUMERIC_8, DEAR_KEY_NUMERIC_8}, 
#endif
#ifdef KEY_NUMERIC_9
 {KEY_NUMERIC_9, DEAR_KEY_NUMERIC_9}, 
#endif
#ifdef KEY_NUMERIC_STAR
 {KEY_NUMERIC_STAR, DEAR_KEY_NUMERIC_STAR}, 
#endif
#ifdef KEY_NUMERIC_POUND
 {KEY_NUMERIC_POUND, DEAR_KEY_NUMERIC_POUND}, 
#endif
#ifdef KEY_NUMERIC_A
 {KEY_NUMERIC_A, DEAR_KEY_NUMERIC_A}, 
#endif
#ifdef KEY_NUMERIC_B
 {KEY_NUMERIC_B, DEAR_KEY_NUMERIC_B}, 
#endif
#ifdef KEY_NUMERIC_C
 {KEY_NUMERIC_C, DEAR_KEY_NUMERIC_C}, 
#endif
#ifdef KEY_NUMERIC_D
 {KEY_NUMERIC_D, DEAR_KEY_NUMERIC_D}, 
#endif
#ifdef KEY_CAMERA_FOCUS
 {KEY_CAMERA_FOCUS, DEAR_KEY_CAMERA_FOCUS}, 
#endif
#ifdef KEY_WPS_BUTTON
 {KEY_WPS_BUTTON, DEAR_KEY_WPS_BUTTON}, 
#endif
#ifdef KEY_TOUCHPAD_TOGGLE
 {KEY_TOUCHPAD_TOGGLE, DEAR_KEY_TOUCHPAD_TOGGLE}, 
#endif
#ifdef KEY_TOUCHPAD_ON
 {KEY_TOUCHPAD_ON, DEAR_KEY_TOUCHPAD_ON}, 
#endif
#ifdef KEY_TOUCHPAD_OFF
 {KEY_TOUCHPAD_OFF, DEAR_KEY_TOUCHPAD_OFF}, 
#endif
#ifdef KEY_CAMERA_ZOOMIN
 {KEY_CAMERA_ZOOMIN, DEAR_KEY_CAMERA_ZOOMIN}, 
#endif
#ifdef KEY_CAMERA_ZOOMOUT
 {KEY_CAMERA_ZOOMOUT, DEAR_KEY_CAMERA_ZOOMOUT}, 
#endif
#ifdef KEY_CAMERA_UP
 {KEY_CAMERA_UP, DEAR_KEY_CAMERA_UP}, 
#endif
#ifdef KEY_CAMERA_DOWN
 {KEY_CAMERA_DOWN, DEAR_KEY_CAMERA_DOWN}, 
#endif
#ifdef KEY_CAMERA_LEFT
 {KEY_CAMERA_LEFT, DEAR_KEY_CAMERA_LEFT}, 
#endif
#ifdef KEY_CAMERA_RIGHT
 {KEY_CAMERA_RIGHT, DEAR_KEY_CAMERA_RIGHT}, 
#endif
#ifdef KEY_ATTENDANT_ON
 {KEY_ATTENDANT_ON, DEAR_KEY_ATTENDANT_ON}, 
#endif
#ifdef KEY_ATTENDANT_OFF
 {KEY_ATTENDANT_OFF, DEAR_KEY_ATTENDANT_OFF}, 
#endif
#ifdef KEY_ATTENDANT_TOGGLE
 {KEY_ATTENDANT_TOGGLE, DEAR_KEY_ATTENDANT_TOGGLE}, 
#endif
#ifdef KEY_LIGHTS_TOGGLE
 {KEY_LIGHTS_TOGGLE, DEAR_KEY_LIGHTS_TOGGLE}, 
#endif
#ifdef BTN_DPAD_UP
 {BTN_DPAD_UP, DEAR_BTN_DPAD_UP}, 
#endif
#ifdef BTN_DPAD_DOWN
 {BTN_DPAD_DOWN, DEAR_BTN_DPAD_DOWN}, 
#endif
#ifdef BTN_DPAD_LEFT
 {BTN_DPAD_LEFT, DEAR_BTN_DPAD_LEFT}, 
#endif
#ifdef BTN_DPAD_RIGHT
 {BTN_DPAD_RIGHT, DEAR_BTN_DPAD_RIGHT}, 
#endif
#ifdef KEY_ALS_TOGGLE
 {KEY_ALS_TOGGLE, DEAR_KEY_ALS_TOGGLE}, 
#endif
#ifdef KEY_BUTTONCONFIG
 {KEY_BUTTONCONFIG, DEAR_KEY_BUTTONCONFIG}, 
#endif
#ifdef KEY_TASKMANAGER
 {KEY_TASKMANAGER, DEAR_KEY_TASKMANAGER}, 
#endif
#ifdef KEY_JOURNAL
 {KEY_JOURNAL, DEAR_KEY_JOURNAL}, 
#endif
#ifdef KEY_CONTROLPANEL
 {KEY_CONTROLPANEL, DEAR_KEY_CONTROLPANEL}, 
#endif
#ifdef KEY_APPSELECT
 {KEY_APPSELECT, DEAR_KEY_APPSELECT}, 
#endif
#ifdef KEY_SCREENSAVER
 {KEY_SCREENSAVER, DEAR_KEY_SCREENSAVER}, 
#endif
#ifdef KEY_VOICECOMMAND
 {KEY_VOICECOMMAND, DEAR_KEY_VOICECOMMAND}, 
#endif
#ifdef KEY_BRIGHTNESS_MIN
 {KEY_BRIGHTNESS_MIN, DEAR_KEY_BRIGHTNESS_MIN}, 
#endif
#ifdef KEY_BRIGHTNESS_MAX
 {KEY_BRIGHTNESS_MAX, DEAR_KEY_BRIGHTNESS_MAX}, 
#endif
#ifdef KEY_KBDINPUTASSIST_PREV
 {KEY_KBDINPUTASSIST_PREV, DEAR_KEY_KBDINPUTASSIST_PREV}, 
#endif
#ifdef KEY_KBDINPUTASSIST_NEXT
 {KEY_KBDINPUTASSIST_NEXT, DEAR_KEY_KBDINPUTASSIST_NEXT}, 
#endif
#ifdef KEY_KBDINPUTASSIST_PREVGROUP
 {KEY_KBDINPUTASSIST_PREVGROUP, DEAR_KEY_KBDINPUTASSIST_PREVGROUP}, 
#endif
#ifdef KEY_KBDINPUTASSIST_NEXTGROUP
 {KEY_KBDINPUTASSIST_NEXTGROUP, DEAR_KEY_KBDINPUTASSIST_NEXTGROUP}, 
#endif
#ifdef KEY_KBDINPUTASSIST_ACCEPT
 {KEY_KBDINPUTASSIST_ACCEPT, DEAR_KEY_KBDINPUTASSIST_ACCEPT}, 
#endif
#ifdef KEY_KBDINPUTASSIST_CANCEL
 {KEY_KBDINPUTASSIST_CANCEL, DEAR_KEY_KBDINPUTASSIST_CANCEL}, 
#endif
#ifdef BTN_TRIGGER_HAPPY
 {BTN_TRIGGER_HAPPY, DEAR_BTN_TRIGGER_HAPPY}, 
#endif
#ifdef BTN_TRIGGER_HAPPY1
 {BTN_TRIGGER_HAPPY1, DEAR_BTN_TRIGGER_HAPPY1}, 
#endif
#ifdef BTN_TRIGGER_HAPPY2
 {BTN_TRIGGER_HAPPY2, DEAR_BTN_TRIGGER_HAPPY2}, 
#endif
#ifdef BTN_TRIGGER_HAPPY3
 {BTN_TRIGGER_HAPPY3, DEAR_BTN_TRIGGER_HAPPY3}, 
#endif
#ifdef BTN_TRIGGER_HAPPY4
 {BTN_TRIGGER_HAPPY4, DEAR_BTN_TRIGGER_HAPPY4}, 
#endif
#ifdef BTN_TRIGGER_HAPPY5
 {BTN_TRIGGER_HAPPY5, DEAR_BTN_TRIGGER_HAPPY5}, 
#endif
#ifdef BTN_TRIGGER_HAPPY6
 {BTN_TRIGGER_HAPPY6, DEAR_BTN_TRIGGER_HAPPY6}, 
#endif
#ifdef BTN_TRIGGER_HAPPY7
 {BTN_TRIGGER_HAPPY7, DEAR_BTN_TRIGGER_HAPPY7}, 
#endif
#ifdef BTN_TRIGGER_HAPPY8
 {BTN_TRIGGER_HAPPY8, DEAR_BTN_TRIGGER_HAPPY8}, 
#endif
#ifdef BTN_TRIGGER_HAPPY9
 {BTN_TRIGGER_HAPPY9, DEAR_BTN_TRIGGER_HAPPY9}, 
#endif
#ifdef BTN_TRIGGER_HAPPY10
 {BTN_TRIGGER_HAPPY10, DEAR_BTN_TRIGGER_HAPPY10}, 
#endif
#ifdef BTN_TRIGGER_HAPPY11
 {BTN_TRIGGER_HAPPY11, DEAR_BTN_TRIGGER_HAPPY11}, 
#endif
#ifdef BTN_TRIGGER_HAPPY12
 {BTN_TRIGGER_HAPPY12, DEAR_BTN_TRIGGER_HAPPY12}, 
#endif
#ifdef BTN_TRIGGER_HAPPY13
 {BTN_TRIGGER_HAPPY13, DEAR_BTN_TRIGGER_HAPPY13}, 
#endif
#ifdef BTN_TRIGGER_HAPPY14
 {BTN_TRIGGER_HAPPY14, DEAR_BTN_TRIGGER_HAPPY14}, 
#endif
#ifdef BTN_TRIGGER_HAPPY15
 {BTN_TRIGGER_HAPPY15, DEAR_BTN_TRIGGER_HAPPY15}, 
#endif
#ifdef BTN_TRIGGER_HAPPY16
 {BTN_TRIGGER_HAPPY16, DEAR_BTN_TRIGGER_HAPPY16}, 
#endif
#ifdef BTN_TRIGGER_HAPPY17
 {BTN_TRIGGER_HAPPY17, DEAR_BTN_TRIGGER_HAPPY17}, 
#endif
#ifdef BTN_TRIGGER_HAPPY18
 {BTN_TRIGGER_HAPPY18, DEAR_BTN_TRIGGER_HAPPY18}, 
#endif
#ifdef BTN_TRIGGER_HAPPY19
 {BTN_TRIGGER_HAPPY19, DEAR_BTN_TRIGGER_HAPPY19}, 
#endif
#ifdef BTN_TRIGGER_HAPPY20
 {BTN_TRIGGER_HAPPY20, DEAR_BTN_TRIGGER_HAPPY20}, 
#endif
#ifdef BTN_TRIGGER_HAPPY21
 {BTN_TRIGGER_HAPPY21, DEAR_BTN_TRIGGER_HAPPY21}, 
#endif
#ifdef BTN_TRIGGER_HAPPY22
 {BTN_TRIGGER_HAPPY22, DEAR_BTN_TRIGGER_HAPPY22}, 
#endif
#ifdef BTN_TRIGGER_HAPPY23
 {BTN_TRIGGER_HAPPY23, DEAR_BTN_TRIGGER_HAPPY23}, 
#endif
#ifdef BTN_TRIGGER_HAPPY24
 {BTN_TRIGGER_HAPPY24, DEAR_BTN_TRIGGER_HAPPY24}, 
#endif
#ifdef BTN_TRIGGER_HAPPY25
 {BTN_TRIGGER_HAPPY25, DEAR_BTN_TRIGGER_HAPPY25}, 
#endif
#ifdef BTN_TRIGGER_HAPPY26
 {BTN_TRIGGER_HAPPY26, DEAR_BTN_TRIGGER_HAPPY26}, 
#endif
#ifdef BTN_TRIGGER_HAPPY27
 {BTN_TRIGGER_HAPPY27, DEAR_BTN_TRIGGER_HAPPY27}, 
#endif
#ifdef BTN_TRIGGER_HAPPY28
 {BTN_TRIGGER_HAPPY28, DEAR_BTN_TRIGGER_HAPPY28}, 
#endif
#ifdef BTN_TRIGGER_HAPPY29
 {BTN_TRIGGER_HAPPY29, DEAR_BTN_TRIGGER_HAPPY29}, 
#endif
#ifdef BTN_TRIGGER_HAPPY30
 {BTN_TRIGGER_HAPPY30, DEAR_BTN_TRIGGER_HAPPY30}, 
#endif
#ifdef BTN_TRIGGER_HAPPY31
 {BTN_TRIGGER_HAPPY31, DEAR_BTN_TRIGGER_HAPPY31}, 
#endif
#ifdef BTN_TRIGGER_HAPPY32
 {BTN_TRIGGER_HAPPY32, DEAR_BTN_TRIGGER_HAPPY32}, 
#endif
#ifdef BTN_TRIGGER_HAPPY33
 {BTN_TRIGGER_HAPPY33, DEAR_BTN_TRIGGER_HAPPY33}, 
#endif
#ifdef BTN_TRIGGER_HAPPY34
 {BTN_TRIGGER_HAPPY34, DEAR_BTN_TRIGGER_HAPPY34}, 
#endif
#ifdef BTN_TRIGGER_HAPPY35
 {BTN_TRIGGER_HAPPY35, DEAR_BTN_TRIGGER_HAPPY35}, 
#endif
#ifdef BTN_TRIGGER_HAPPY36
 {BTN_TRIGGER_HAPPY36, DEAR_BTN_TRIGGER_HAPPY36}, 
#endif
#ifdef BTN_TRIGGER_HAPPY37
 {BTN_TRIGGER_HAPPY37, DEAR_BTN_TRIGGER_HAPPY37}, 
#endif
#ifdef BTN_TRIGGER_HAPPY38
 {BTN_TRIGGER_HAPPY38, DEAR_BTN_TRIGGER_HAPPY38}, 
#endif
#ifdef BTN_TRIGGER_HAPPY39
 {BTN_TRIGGER_HAPPY39, DEAR_BTN_TRIGGER_HAPPY39}, 
#endif
#ifdef BTN_TRIGGER_HAPPY40
 {BTN_TRIGGER_HAPPY40, DEAR_BTN_TRIGGER_HAPPY40} 
#endif
};